### ISSUE TITLE
Aplayer  错误

### ISSUE THREAD

**Issue by KumaNNN** [u2sb/hexo-tag-mmedia#11]
Aplayer 播放器，播放音频文件，拖动进度条时，发生错误，导致无法播放。
```
An audio error has occurred.
```
错误信息来自[  APlayer.min.js](https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.js) 。

[APlayer.zip](https://github.com/u2sb/hexo-tag-mmedia/files/5009499/APlayer.zip)

**Comment by KumaNNN** [comment]
@u2sb

**Comment by MonoLogueChi** [comment]
mmedia插件只是负责插入媒体标签，这个错误你可以到 Aplayer 仓库下提 issue
