### ISSUE TITLE
有报错，不知什么原因

### ISSUE THREAD

**Issue by guhailong18** [u2sb/hexo-tag-mmedia#15]
![image](https://user-images.githubusercontent.com/56160866/102853788-fbac0700-445b-11eb-9b3a-c141895019a4.png)
望大佬看看

**Comment by MonoLogueChi** [comment]
AplayerList 不要用，没有充分的测试，下个版本会删掉这个功能

**Comment by MonoLogueChi** [comment]
请更新 1.x 版本
