### ISSUE TITLE
hls_cdn的地址有问题

### ISSUE THREAD

**Issue by dreamCN** [u2sb/hexo-tag-mmedia#16]
![image](https://user-images.githubusercontent.com/9692375/103873011-265bb800-510a-11eb-90cc-2f896308b348.png)
hls_cdn的地址有问题，应改https://cdn.jsdelivr.net/npm/hls.js/dist/hls.min.js

**Comment by MonoLogueChi** [comment]
下个版本修复，当前版本可以通过自定义配置解决
