### ISSUE TITLE
在同一个页面引入多个meting标签会报错

### ISSUE THREAD

**Issue by W4J1e** [u2sb/hexo-tag-mmedia#19]
您好，我做了个歌单页面，此前的主题自带有aplayer和meting，所以按照html语法来写就可以了。
换成butterfly主题后，我使用hexo-tag-mmedia插件，在同一个页面写了多个标签之后会重复加载aplayer播放器，并且控制台就会报错，还有网易云歌单是不是无法获取了？
![屏幕截图 2021-06-26 124228](https://user-images.githubusercontent.com/74824162/123502071-01d5a700-d67c-11eb-9a6d-ff63ae320a4e.jpg)
这是原主题，貌似网易云歌单同样获取不到了，但是aplayer只需加载一次。
![2](https://user-images.githubusercontent.com/74824162/123502124-5ed15d00-d67c-11eb-8a82-a5b0a2ad99f6.jpg)
谢谢了~

**Comment by MonoLogueChi** [comment]
[MetingJS#56](https://github.com/metowolf/MetingJS/issues/56), [MetingJS#58](https://github.com/metowolf/MetingJS/issues/58)

**Comment by W4J1e** [comment]
> [MetingJS#56](https://github.com/metowolf/MetingJS/issues/56), [MetingJS#58](https://github.com/metowolf/MetingJS/issues/58)

网易云音乐api目前已恢复。但是请问有没有办法不要在同一个页面重复引入播放器？

**Comment by MonoLogueChi** [comment]
> > [MetingJS#56](https://github.com/metowolf/MetingJS/issues/56), [MetingJS#58](https://github.com/metowolf/MetingJS/issues/58)
> 
> 网易云音乐api目前已恢复。但是请问有没有办法不要在同一个页面重复引入播放器？

不贴代码，不上示例页，不知道你傻问题

**Comment by MonoLogueChi** [comment]
有解决思路了，懒得搞，等闲得无聊的时候再搞

- [x] 解决重复加载问题

**Comment by W4J1e** [comment]
代码如下：
``` markdown
{% note default simple %}
网易云歌单 不只是后摇
{% endnote %}

{% mmedia "meting" "server:netease" "type:playlist" "id:2709509873" "volume:0.66" "mutex:true" %}

{% note default simple %}
QQ音乐歌单  向死而生|LanaDelRey
{% endnote %}
{% mmedia "meting" "server:tencent" "type:playlist" "id:3806422707" "volume:0.66" "mutex:true" "list-folded:true" %}

{% note default simple %}
QQ音乐歌单  撒旦歌者|MarilynManson
{% endnote %}
{% mmedia "meting" "server:tencent" "type:playlist" "id:1779394777" "volume:0.66" "mutex:true" "list-folded:true" %}

{% note default simple %}
QQ音乐歌单  三十而立|胡彦斌
{% endnote %}
{% mmedia "meting" "server:tencent" "type:playlist" "id:3806424693" "volume:0.66" "mutex:true" "list-folded:true" %}
```

这是部分代码，另外部分写法和上述一样。其中`{% note default simple %}xxx{% endnote %} `为hexo博客主题的标签，下方为hexo-tag-mmedia标签。目前没有示例页面，我换成了下面的写法，效果如上面图一所示，报错也如图一。就是一个页面多次引入播放器感觉有点浪费资源，相信您理解我的意思。
``` html
`<meting-js
	server="netease"
	type="playlist"
	id="2709509873"
	list-folded="false"
	mutex="true">
</meting-js>`
```

**Comment by appotry** [comment]
使用 injector 来加载 js 和 css @MonoLogueChi 
官方文档如下

https://hexo.io/zh-cn/api/injector#%E6%A6%82%E8%A6%81

这个应该可以解决这个问题

**Comment by MonoLogueChi** [comment]
> 使用 injector 来加载 js 和 css @MonoLogueChi 官方文档如下
> 
> https://hexo.io/zh-cn/api/injector#%E6%A6%82%E8%A6%81
> 
> 这个应该可以解决这个问题

使用 Injector 会导致在所有页面都引入相关js文件，不能仅在特定页面注入

**Comment by appotry** [comment]
> > 使用 injector 来加载 js 和 css @MonoLogueChi 官方文档如下
> > https://hexo.io/zh-cn/api/injector#%E6%A6%82%E8%A6%81
> > 这个应该可以解决这个问题
> 
> 使用 Injector 会导致在所有页面都引入相关js文件，不能仅在特定页面注入

使用js判断本页面是否存在mmedia相关的class，如果存在才加载对应的js css，这样做如何

另外还有一个办法，在[Post Front-matter](https://github.com/blinkfox/hexo-theme-matery#detailed-front-matter-options)中添加一个判断开关，参数为true时，才加载对应js css，把是否加载权限给每篇文章头部控制，交给用户

**Comment by MonoLogueChi** [comment]
> > > 使用 injector 来加载 js 和 css @MonoLogueChi 官方文档如下
> > > https://hexo.io/zh-cn/api/injector#%E6%A6%82%E8%A6%81
> > > 这个应该可以解决这个问题
> > 
> > 
> > 使用 Injector 会导致在所有页面都引入相关js文件，不能仅在特定页面注入
> 
> 使用js判断本页面是否存在mmedia相关的class，如果存在才加载对应的js css，这样做如何
> 
> 另外还有一个办法，在[Post Front-matter](https://github.com/blinkfox/hexo-theme-matery#detailed-front-matter-options)中添加一个判断开关，参数为true时，才加载对应js css，把是否加载权限给每篇文章头部控制，交给用户

这个方法也不太好，使用过于麻烦，而且在多个地方配置不容易维护

使用了一种比较特殊的方法，每个标签仅仅是添加数据，在每个页面加载一个大约2kb的js文件，负责统一加载js和初始化播放器
