### ISSUE TITLE
mmedias 能使用meting自定义歌单吗？

### ISSUE THREAD

**Issue by chunxiao01** [u2sb/hexo-tag-mmedia#22]
使用meting，歌曲来源可以自由混合组成歌单吗？
`
 {% mmedia "meting" "server=netease"	"type=song"	"id=1325905146" %}

 {% mmedia "meting" "auto=https://y.qq.com/n/yqq/song/001RGrEX3ija5X.html" %}
`

**Comment by MonoLogueChi** [comment]
不可以
