### ISSUE TITLE
bilibili会导致后面的markdown解析出问题？

### ISSUE THREAD

**Issue by appotry** [u2sb/hexo-tag-mmedia#24]
bilibili tag 放前面

后面的markdown 语法，比喻 markdown表格渲染就会出错，以文本形式出现

其他人有发现这个问题么？ 

bilibili 放到 西瓜 和 artplayer 后面会渲染不出来，这三个放一个页面测试时发现的

```
#hexo -v
INFO  Validating config
hexo: 6.1.0
hexo-cli: 4.3.0
os: linux 5.10.60-qnap Debian GNU/Linux 11 (bullseye) 11 (bullseye)
node: 17.8.0
v8: 9.6.180.15-node.16
uv: 1.43.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.18.1
modules: 102
nghttp2: 1.47.0
napi: 8
llhttp: 6.0.4
openssl: 3.0.2+quic
cldr: 40.0
icu: 70.1
tz: 2021a3
unicode: 14.0
ngtcp2: 0.1.0-DEV
nghttp3: 0.1.0-DEV
```

**Comment by YuanZhou314** [comment]
不光是表格，它就只能页面单独放视频，不能加其他文字……

**Comment by MonoLogueChi** [comment]
好像是高版本的HEXO才会有这个问题，暂时不清楚是什么原因，可能与渲染器有关，可以使用低版本的HEXO

**Comment by MonoLogueChi** [comment]
@appotry  @YuanZhou314  经测试，发现是 marked 问题，使用 markdown-it 渲染可解决问题

![图片](https://github.com/u2sb/hexo-tag-mmedia/assets/26868745/363bf192-fa9c-4c47-a9cd-8805f13a239e)
