### ISSUE TITLE
哔哩哔哩的标签能不能添加关闭"autoplay"的功能

### ISSUE THREAD

**Issue by nirvana6** [u2sb/hexo-tag-mmedia#25]
如题. 如果使用官方的ifram方法, 在src尾部添加 `&autoplay=0`即可关闭视频的自动播放, 但是用 `hexo-tag-mmedia`不行. 但用管理员的插件习惯了. 

请问管理员能不能给哔哩哔哩的标签增加 disable autoplay的功能? 

多谢了.

**Comment by MonoLogueChi** [comment]
此插件已经不再维护，需要的花可以fork一份自行维护

**Comment by nirvana6** [comment]
好的. 多谢贡献.

**Comment by nirvana6** [comment]
好的, 多谢贡献.
