### ISSUE TITLE
MetingJS: An audio error has occurred

### ISSUE THREAD

**Issue by w753621** [u2sb/hexo-tag-mmedia#8]
使用hexo-tag-aplayer及本版本在播放部分歌曲都會出現這個錯誤: An audio error has occurred, player will skip forward in 2 second
已確認歌曲有版權且在hexo s下可以播放 
MetingJS:netease

**Comment by MonoLogueChi** [comment]
可能是后端解析问题，换个解析源试一下，netease真的不好用
