### ISSUE TITLE
使用哔哩哔哩在手机端的样式问题

### ISSUE THREAD

**Issue by UntaggedRui** [u2sb/hexo-tag-mmedia#9]
目前直接插入的话在手机端会很长。
{% bilibili "bvid:BV1Xt411n7iJ" "quality:high" "danmaku" "allowfullscreen" %}
如果使用如下方式插入样式似乎好看点。
```
{% raw %}

<div style="position: relative; width: 100%; height: 0; padding-bottom: 75%;">
<iframe src="//player.bilibili.com/player.html?aid=60016166&bvid=BV1Xt411n7iJ&cid=104514776&page=1" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullscreen="true" style="position: absolute; width: 100%; height: 100%; Left: 0; top: 0;" ></iframe></div>

{% endraw %}
```
下面是显示截图
![显示不好看](https://s1.ax1x.com/2020/07/26/aphp5Q.jpg)
详情可以用手机访问https://zhangrui_cs.gitee.io/posts/bilibili-videos-in-hexo/
请问能不能优化下手机端的显示方式呢

**Comment by MonoLogueChi** [comment]
感谢反馈，以前也一直没有找打合适的手机端适配方案，会想办法改进的

**Comment by UntaggedRui** [comment]
> 感谢反馈，以前也一直没有找打合适的手机端适配方案，会想办法改进的

请问怎么使用更新后的代码呢？我是用npm安装的。现在是用npm更新还是需要用源码编译？

**Comment by MonoLogueChi** [comment]
> 请问怎么使用更新后的代码呢？我是用npm安装的。现在是用npm更新还是需要用源码编译？

发布了新的包，更新到 0.1.7 即可

**Comment by UntaggedRui** [comment]
> > 请问怎么使用更新后的代码呢？我是用npm安装的。现在是用npm更新还是需要用源码编译？
> 
> 发布了新的包，更新到 0.1.7 即可

我这边卸载后在安装还是0.1.6.我再等等吧
